
#
#services:
#  mysql:
#    image: mysql:8.0
#    container_name: mysql_container
#    environment:
#      MYSQL_ROOT_PASSWORD: 123123
#      MYSQL_DATABASE: blogCocina_db
#    ports:
#      - "3307:3306"
#    volumes:
#      - mysql_data:/var/lib/mysql
#    networks:
#      - springboot-mysql-network
#
#  app:
#    build: .
#    container_name: springboot_app
#    ports:
#      - "8080:8080"
#    depends_on:
#      - mysql
#    environment:
#      DB_URL: jdbc:mysql://mysql:3306/blogCocina_db?createDatabaseIfNotExist=true
#      DB_USER: root
#      DB_PASSWORD: 123123
#    networks:
#      - springboot-mysql-network
#
#volumes:
#  mysql_data:
#
#networks:
#  springboot-mysql-network:



#version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_container
    environment:
      POSTGRES_DB: blogCocina_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123123
    ports:
      - "5433:5432"  # expone el puerto 5432 (Postgres) en el host como 5433
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - springboot-postgres-network

  app:
    build: .
    container_name: springboot_app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      JDBC_DATABASE_URL: jdbc:postgresql://postgres:5432/blogCocina_db
      JDBC_DATABASE_USERNAME: root
      JDBC_DATABASE_PASSWORD: 123123
    networks:
      - springboot-postgres-network

volumes:
  postgres_data:

networks:
  springboot-postgres-network:


